version: "3"
services:
  spring-app:
    image: products-app
    ports:
      - "8081:8080"
    environment:
      DB_SERVER: database
      DB_PORT: 3306
      DB_NAME: products
      DB_USERNAME: kiii
      DB_PASSWORD: kiii
    depends_on:
      - database
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: kiii
      MYSQL_DATABASE: products
      MYSQL_USER: kiii
      MYSQL_PASSWORD: kiii
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: